### PR TITLE
add SHVQE script

### PR DESCRIPTION
**Pull request by royess**
As mentioned in Issue #190, I want to contribute a script of Schrodinger-Heisenberg quantum variational eigensolver (SHVQE) with quantum architecture search.

### CODE REVIEW

**Comment by refraction-ray** [comment]
Thanks for the contribution. If applicable, do you have some remarks on the accuracy performance?

**Comment by refraction-ray** [comment]
please use black to format the code

**Comment by royess** [comment]
> please use black to format the code

It is solved in the new commit.



> Thanks for the contribution. If applicable, do you have some remarks on the accuracy performance?

I haven't done a performance benchmark on H6 Hamiltonian, provided in the `examples` directory.

Based on my previous experiments on OH Hamiltonian and also the data in the original paper, SHVQE features provide higher accuracy when circuit depth is limited. The accuracy grows when (Schrodinger) circuit depth increases.

**Comment by refraction-ray** [comment]
@all-contributors please add @royess for example

**Pull request merged**
