### PR TITLE
Backend agnostic implementation of quantum Hamiltonian generation

### LINKED ISSUE #161: Backend agnostic implementation of quantum Hamiltonian generation
## Task description

Revise the following code using tensorcircuit backend API instead of tf API, making it backend agnostic

## Implementation

Revise the following code using tensorcircuit backend API instead of tf API, making it backend agnostic, at least work for both tensorflow and jax (the efficiency could also be benchmarked)

https://github.com/tencent-quantum-lab/tensorcircuit/blob/master/tensorcircuit/quantum.py#L1167-L1468

You can add the missing backend method in `/tensorcircuit/backends` like the bitwise shift operations if necessary

## Requirements

Difficulty: ★★

### PR DESCRIPTION
**Pull request by king-p3nguin**
- Resolve #161
- Add script to benchmark sparse hamiltonian building

(I am contributing to this project as a unitaryHACK participant)

### CODE REVIEW

**Comment by refraction-ray** [comment]
thanks for the nice contribution. could you also include an example script in `/examples` to both check the correctness and compare the efficiency of the sparse Hamiltonian generation for different backends? (say generate Hamiltonian for several typical systems in O(20) qubits). I can also utilize the same script to benchmark the efficiency between previous impl. and the current one in case any performance degradation.

**Comment by king-p3nguin** [comment]
I noticed that `examples/hamiltonian_building.py` does the benchmark for the `numpy` backend, so I also added the `jax` and `tensorflow` backends in the script.

**Comment by refraction-ray** [comment]
LGTM, I have further added jit for these functions to improve the efficiency

**Comment by refraction-ray** [comment]
@all-contributors please add @king-p3nguin for example

**Pull request merged**
