### PR TITLE
rewrite `cvar`

### PR DESCRIPTION
**Pull request by FelixXu35**
let the function directly return the CVaR value of a distribution.
it was not straightforward to calculate with results from the previous `cvar`.
The function was tested and reformatted.

### CODE REVIEW

**Comment by refraction-ray** [comment]
are you sure the new impl is compitible with old dqas application? i.e. the return of the function is unchanged after the refactoring?

**Comment by FelixXu35** [comment]
Good afternoon!
The return is different. It was a sorted and truncated list of values. I think this return is difficult to be used in the calculation of CVaR value since the sorted list of possibilities is unknown to users.
So I let the output to be the CVaR value.
I didn't consider that you may be using this function somewhere (i searched the library and didn't find any). Maybe I shall write a new function (like `cvar_value`) instead of rewriting the previous one?

**Comment by refraction-ray** [comment]
yes, please dont modify the functions in applications submodule unless you know what you are doing, they may be called implicitly in some twisted patten (and actually the code for this submodule is deprecated and not recommended to use for general users anyway). If you want to illustrate the usage of cvar, just write your own cvar impl on the jupyter tutorial directly. Or add a cvar qaoa example at /examples as a python script.

**Comment by FelixXu35** [comment]
okay will do

**Pull request closed without merging**
