### PR TITLE
Add stabilizer simulation example utilizing stim backend

### LINKED ISSUE #211: Stabilizer simulation example utilizing stim backend
## Task description

Add an example python script `stabilizer_stim_sim.py` in `/examples` which showcases stabilizer circuit simulation using tc interface with stim backend.

## Implementation

The script includes:
1. Clifford circuit with mid-circuit measurement defined in tc
2. Transform the circuit object into Stim circuit object with the helper function defined in the same script (input: tc circuit, output: stim circuit)(can utilize `c._qir` and `c._extra_qir`, using `c.measure_instruction` to get the mid circuit measurement recorded in extra_qir and using `c.mid_measurement` for the real functionality)
3. Simulate the circuit in stim and extract the stabilizer tableau 
4. Compute the entanglement entropy of the output state with the helper function defined in the same script (input: stabilizer tableau representation, output: entanglement entropy value) (see Ref 3, it would be better to try hard to accelerate this function)
5. Validate the correctness by directly computing entanglement from tc (mid-circuit measurement results might require to be averaged)

## References:

1. https://github.com/tencent-quantum-lab/tensorcircuit/issues/159
2. https://github.com/quantumlib/Stim
3. https://quantumcomputing.stackexchange.com/questions/16718/measuring-entanglement-entropy-using-a-stabilizer-circuit-simulator
4. https://arxiv.org/abs/quant-ph/0406196

### PR DESCRIPTION
**Pull request by king-p3nguin**
Resolve #211

How the example works:
1. Creates random Clifford circuit with mid-circuit measurement. Mid-circuit measurement is inserted only when post-selection to zero state is possible.
2. Convert TensorCircuit's circuit to a Stim circuit via qir and extract the stabilizer tableau.
3. Calculate the entanglement entropy from the stabilizer tableau.
4. Validate the correctness of the entanglement entropy using TensorCircuit's function.

Output:

```
           ┌───┐┌───┐┌───┐┌───┐                                           ┌───┐┌───┐┌───┐┌───┐┌───┐               ┌───┐┌───┐             
 q_0: ─────┤ H ├┤ H ├┤ S ├┤ Z ├───────────────────────────────────────────┤ X ├┤ H ├┤ X ├┤ Z ├┤ Y ├───────────────┤ X ├┤ H ├─────────────
           ├───┤├───┤└───┘└───┘┌───┐     ┌───┐┌───┐               ┌─┐┌───┐└─┬─┘└───┘└─┬─┘├───┤├───┤┌───┐          └─┬─┘└───┘┌─┐          
 q_1: ─────┤ X ├┤ H ├──────────┤ X ├──■──┤ H ├┤ Y ├───────────────┤M├┤ H ├──┼─────────■──┤ X ├┤ Z ├┤ X ├────────────┼───────┤M├──────────
           ├───┤├───┤     ┌───┐└─┬─┘  │  ├───┤└───┘┌───┐┌───┐     └╥┘└───┘  │       ┌───┐├───┤└┬─┬┘└───┘┌───┐┌───┐  │       └╥┘          
 q_2: ──■──┤ X ├┤ X ├──■──┤ S ├──┼────┼──┤ S ├──■──┤ X ├┤ Y ├──────╫────────┼───────┤ X ├┤ H ├─┤M├───■──┤ S ├┤ H ├──┼────────╫───────────
        │  ├───┤└─┬─┘┌─┴─┐├───┤  │    │  ├───┤  │  ├───┤├───┤┌───┐ ║        │       └─┬─┘└───┘ └╥┘ ┌─┴─┐└───┘└───┘  │  ┌───┐ ║ ┌───┐┌───┐
 q_3: ──┼──┤ H ├──┼──┤ X ├┤ H ├──┼────┼──┤ Z ├──┼──┤ Y ├┤ Z ├┤ H ├─╫────────┼─────────┼─────────╫──┤ X ├───────■────┼──┤ H ├─╫─┤ X ├┤ S ├
        │  ├───┤  │  ├───┤└───┘  │    │  ├───┤  │  ├───┤├───┤├───┤ ║ ┌───┐  │  ┌───┐  │         ║  └───┘       │    │  └───┘ ║ └─┬─┘└───┘
 q_4: ──┼──┤ X ├──■──┤ S ├───────■────┼──┤ Y ├──┼──┤ Z ├┤ Y ├┤ S ├─╫─┤ Y ├──┼──┤ H ├──┼─────────╫──────────────┼────┼────────╫───┼───────
        │  ├───┤┌───┐└───┘          ┌─┴─┐├───┤  │  └┬─┬┘└───┘└───┘ ║ ├───┤  │  ├───┤  │  ┌───┐  ║  ┌───┐ ┌─┐   │    │  ┌───┐ ║   │       
 q_5: ──┼──┤ S ├┤ X ├───────────────┤ X ├┤ H ├──┼───┤M├────────■───╫─┤ Z ├──┼──┤ Z ├──┼──┤ Z ├──╫──┤ Z ├─┤M├───┼────■──┤ Z ├─╫───┼───────
        │  ├───┤├───┤┌───┐┌───┐┌───┐├───┤├───┤  │   └╥┘ ┌───┐  │   ║ ├───┤  │  └───┘  │  └───┘  ║  └───┘ └╥┘   │       └───┘ ║   │       
 q_6: ──┼──┤ X ├┤ Z ├┤ S ├┤ X ├┤ Z ├┤ H ├┤ Z ├──┼────╫──┤ Z ├──┼───╫─┤ Y ├──┼─────────┼─────────╫─────────╫────┼─────────────╫───┼───────
        │  └─┬─┘├───┤├───┤├───┤├───┤└───┘└───┘  │    ║  └───┘  │   ║ └───┘  │  ┌───┐  │  ┌───┐  ║         ║  ┌─┴─┐┌───┐┌───┐ ║   │       
 q_7: ──┼────┼──┤ H ├┤ X ├┤ X ├┤ Y ├────────────┼────╫─────────┼───╫───■────┼──┤ H ├──■──┤ X ├──╫─────────╫──┤ X ├┤ X ├┤ H ├─╫───┼───────
      ┌─┴─┐  │  ├───┤├───┤├───┤└───┘          ┌─┴─┐  ║  ┌───┐  │   ║ ┌─┴─┐  │  ├───┤ ┌─┐ ├───┤  ║  ┌───┐  ║  ├───┤└───┘└───┘ ║   │       
 q_8: ┤ X ├──┼──┤ Z ├┤ Y ├┤ Z ├───────────────┤ X ├──╫──┤ Z ├──┼───╫─┤ X ├──■──┤ H ├─┤M├─┤ H ├──╫──┤ Z ├──╫──┤ H ├───────────╫───┼───────
      └───┘  │  ├───┤├───┤├───┤               └───┘  ║  └───┘┌─┴─┐ ║ ├───┤┌───┐├───┤ └╥┘ ├───┤  ║  └───┘  ║  └───┘           ║   │  ┌───┐
 q_9: ───────■──┤ H ├┤ Y ├┤ H ├──────────────────────╫───────┤ X ├─╫─┤ S ├┤ Z ├┤ H ├──╫──┤ S ├──╫─────────╫──────────────────╫───■──┤ X ├
                └───┘└───┘└───┘                      ║       └───┘ ║ └───┘└───┘└───┘  ║  └───┘  ║         ║                  ║      └───┘
c: 10/═══════════════════════════════════════════════╩═════════════╩══════════════════╩═════════╩═════════╩══════════════════╩═══════════
                                                     0             1                  2         3         4                  5           
Stim Entanglement Entropy: 1.3862943611198906
TensorCircuit Entanglement Entropy: 1.3862943618593357
```

### CODE REVIEW

**Comment by king-p3nguin** [comment]
Hi @AbdullahKazi500, I modified your code to calculate the correct entanglement entropy and support mid-circuit measurement correctly, and I would not mind splitting the bounty with you. Please let me know what you think.

**Comment by refraction-ray** [comment]
Thanks for the contribution, the PR now looks better. However, I can still find the inconsistence of the entropy calculation with ``num_qubits = 10, depth = 6``, where stim gives EE value 0 while tc gives 0.693. Could you debug the issue of this inconsistency? It would also be better to generalize the code a bit to support any partition for EE calculation instead of half chain now as `num_qubits//2`

Attached is the circuit yielding inconsistent results

Screen Shot 2024-06-11 at 10 38 34 AM

**Comment by king-p3nguin** [comment]
@refraction-ray I was able to fix the bug in the example. I have tested the code with `num_qubits = 10`, `depth=1~30`, `cut = [i for i in range(num_qubits // 3)]`.

- tc to stim circuit conversion via qir does not seem a good idea because when converted to qir, all the mid-measurements are pushed to the end of the circuit, so I just created a list of operations.
- `np.isclose()` is used to check the probability since even if the probability is close to 1.0, `p < 1.0` can be `True` due to floating-point error.

**Comment by refraction-ray** [comment]
Thanks for your contribution. I'll assign the issue to both of you first and then further testing the code :)

> all the mid-circuit measurements are pushed to the end of the circuit, so I just created a list of operations

That's why we need `c.measurement_instruction()` for each mid-circuit measurement to record, and `merge_qir` to ensure the order of gates and mid-circuit measurements

**Comment by refraction-ray** [comment]
@all-contributors please add @AbdullahKazi500  for example

**Pull request merged**
